version: '3.9'

services:
  backend:
    build: ./backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge